# The configurations in this file are shared across all applications.
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # Allow the services to register more quickly in a demo environment.
  instance:
    leaseRenewalIntervalInSeconds: 1
    hostname: localhost
